on:
  push:
    branches:
      - main

jobs:
  run_pull:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: connect ssh
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}
          exit
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}
      - name: ls
        run:
          ls
        
